// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './supabase.types';

const SUPABASE_URL = "https://jbsxzxavlbiypayaikjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impic3h6eGF2bGJpeXBheWFpa2pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NjYzNTMsImV4cCI6MjA2NjM0MjM1M30.OHHI8XXXCtuOYZcKDZzdfDsyPUqvwvDTBo71yP1jRv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});